To address #110 and #109
uoaerg/draft-tsvwg-dscp-considerations pull request #112
Opened 2023-03-02 08:19 UTC by gorryfair

Comments from John Scudder

2023-03-02 09:17 UTC, ana-cc requested changes
Let me know if you agree with the comments and I can make the changes to the pr

2023-03-02 09:17 UTC, ana-cc commented on draft-ietf-tsvwg-dscp-considerations-13.xml
> +        bit position with value '0' or '1').
should we re-add the either before '0'?

2023-03-02 09:17 UTC, ana-cc commented on draft-ietf-tsvwg-dscp-considerations-13.xml
> +	    previously recommended a local use of DSCP values 0x01, 0x03, 0x05 and 0x07
this is clearer to me

2023-03-02 09:17 UTC, ana-cc commented on draft-ietf-tsvwg-dscp-considerations-13.xml
> +	that sets the higher order bits to 0b11 (see Section 4.2.1 of this document).</t>
change :
except for packets with a DSCP that sets the higher order bits to 0b11 (see Section 4.2.1 of this document).
to:
except for packets carrying a DSCP with the format  0b11xxxx (i.e. setting the higher order bits to 0b11, see Section 4.2.1 of this document)/

2023-03-02 09:17 UTC, ana-cc commented on draft-ietf-tsvwg-dscp-considerations-13.xml
>  ]]></artwork>
there is an extra table very similar to the previous one, I think I prefer the first one because we use 'Bleaching' elsewhere for a different behaviour

2023-03-02 09:17 UTC, ana-cc commented on draft-ietf-tsvwg-dscp-considerations-13.xml
>          tag that allows Ethernet frames to be marked as one of eight priority values <xref
field, which includes

2023-03-02 09:17 UTC, ana-cc commented
Let me know if you agree with the comments, I can then make these changes.

2023-03-02 15:57 UTC, gorryfair commented on draft-ietf-tsvwg-dscp-considerations-13.xml
> +	    previously recommended a local use of DSCP values 0x01, 0x03, 0x05 and 0x07
OK

2023-03-02 15:57 UTC, gorryfair commented on draft-ietf-tsvwg-dscp-considerations-13.xml
> +	that sets the higher order bits to 0b11 (see Section 4.2.1 of this document).</t>
OK

2023-03-02 15:58 UTC, gorryfair commented on draft-ietf-tsvwg-dscp-considerations-13.xml
>  ]]></artwork>
The first has weird abbreviations, so we could say "re-marked fm AF11..41" perhaps?

2023-03-02 15:59 UTC, gorryfair commented on draft-ietf-tsvwg-dscp-considerations-13.xml
>          tag that allows Ethernet frames to be marked as one of eight priority values <xref
OK

2023-03-03 11:14 UTC, ana-cc commented on draft-ietf-tsvwg-dscp-considerations-13.xml
>  ]]></artwork>
OK, making the change

2023-03-03 11:19 UTC, ana-cc commented
changes all made - if you're happy then I can merge and upload!

2023-03-03 12:18 UTC, merged