Resolving editorial review from RG
uoaerg/draft-tsvwg-dscp-considerations pull request #43
Opened 2022-08-04 10:14 UTC by gorryfair

Editorial changes from TSVWG review. 
Two issues remain: - one related to unexpected DSCP and one related to text describing intent of DS wrt to ToS.

2022-08-04 10:19 UTC, gorryfair commented
Expected to close issue #44 when merged.

2022-08-09 12:56 UTC, ana-cc requested changes
...(in which packets marked with a LE DSCP that were  intended to be forwarded with lower precedence thn default are instead forwarded with a precedence higher than used for BE packets, see section 6 of <xref target="RFC8622">)

this should be:

... (in which packets marked with a DSCP that were intended to be forwarded with higher precedence than default are instead forwarded with a precedence lower than used for BE packets, see section 6 of <xref target="RFC8622">)

2022-08-09 12:56 UTC, ana-cc commented on draft-ietf-tsvwg-dscp-considerations-04.xml
> +        precedence thn default are instead forwarded with
s/thn/than

2022-08-09 12:56 UTC, ana-cc commented on draft-ietf-tsvwg-dscp-considerations-04.xml
> +        precedence thn default are instead forwarded with
Also, should it not be the other way around:

       (in which packets marked with a DSCP that were intended to be forwarded with higher precedence than default are instead forwarded with a precedence lower than used for BE packets, see section 6 of <xref target="RFC8622">)

2022-08-09 13:30 UTC, ana-cc requested changes

2022-08-09 13:30 UTC, ana-cc commented on draft-ietf-tsvwg-dscp-considerations-04.xml
> -        inversion in the treatment (in which packets marked with a LE DSCP
I'm sorry I still don't get this - we say it's good to avoid choosing a dscp that can be remarked to LE - surely this is a priority inversion because the packets were supposed to be forwarded with *higher* assurance, but then they get remarked to LE, which is lower assurance than default. Is this not what the text should say, instead of the other way around?

2022-08-09 13:36 UTC, gorryfair commented on draft-ietf-tsvwg-dscp-considerations-04.xml
> +        precedence thn default are instead forwarded with
Please see proposed updated text.

2022-08-09 13:37 UTC, gorryfair commented on draft-ietf-tsvwg-dscp-considerations-04.xml
> -        inversion in the treatment (in which packets marked with a LE DSCP
Reading again.

2022-08-09 13:45 UTC, ana-cc approved these changes

2022-08-09 13:45 UTC, merged